### ISSUE TITLE
Solution 3000 Programming

### ISSUE THREAD

**Issue by t3h-n00b** [mag1024/bosch-alarm-mode2#1]
Hi There,

Trying to give this a crack - can't seem to connect to the unit.

You mention
> To enable the "Mode 2" API in the panel, in the set the "Automation / Remote App" section of the panel settings, set the "Automation Device" to "Mode 2", and use the "Automation Passcode".

However this option doesn't seem to exist in the A-Link software. Any ideas on how to activate using A-Link?
Thanks!

**Comment by EHylands** [comment]
Hi @t3h-n00b ,
Solution3000 Mode2 implementation on firmware is minimal and undocumented at best...

There are no automation passcode on Solution panels. RSC pass code needs to be use, but with a different command than on US panels.

Only some command format 1 call work.

Subscriptions for pushed notifications are not working yet (need to pool panel at planed interval) 

Please see [Sanjay900](https://github.com/sanjay900/solution3000-home-assistant) project in that regard on home assistant.

**Comment by t3h-n00b** [comment]
Hey @EHylands - thats great, thanks for the pointer, will check it out!

**Comment by mag1024** [comment]
Unfortunately, I don't have any experience with the Solution series -- I have a G series panel myself.
Looking at the protocol docs, there Mode 2 does have commands for both automation (which is what the current implementation is using) and user-based (using pin/application passcode) authentication. I can give you some pointers on how to modify the implementation to use, but it may not be worthwhile, given Eric's response.

**Comment by t3h-n00b** [comment]
@mag1024  - thanks for the reply. Happy to take the guidance and give it a shot and see where I get to.

**Comment by mag1024** [comment]
First let's confirm that the authentication is the problem.
What happens when you try to run bin/alarm.py? Does it even get to the stage of attempting and failing to authenticate? i.e. do you get an exception re: "Not Authorized", or does it fail even earlier?

**Comment by t3h-n00b** [comment]
Seems to fail straight away - not clear if it's auth:

`bosch-alarm-mode2 % python3 bin/alarm.py --host 192.168.1.10 --port 7700 -P 00000000
DEBUG: Using selector: KqueueSelector
DEBUG: Panel created
INFO: Connecting to 192.168.1.10:7700...
DEBUG: >> b'\x01\x0b\x06\x0100000000\x00'
INFO: Connection terminated.`

**Comment by EHylands** [comment]
Hi @mag1024 
Which panel are you testing on ?
I was never able to allow user to log in with 0x06 command on solution panel.
Resorted to use `Login Remote User [0x3E]` command.
Curious to see if you are getting 0x06 command to run properly with solution panels.

**Comment by mag1024** [comment]
@EHylands I have the B8512G, and 0x06 works for me. There's also 0x62, which is supposed to be a combination of 0x06 and 0x3E -- but I haven't tried it. When you say that "subscriptions for pushed notifications are not working" is that because the Sanjay's library doesn't implement them, or because of another limitation of the Solutions panels?

@t3h-n00b Does the same thing happen if you replace [this](https://github.com/mag1024/bosch-alarm-mode2/blob/master/bosch_alarm_mode2/panel.py#L216) 0x01 with 0x02 (requesting *User Based Remote Access*, instead of the *Automation* user)?

**Comment by t3h-n00b** [comment]
@mag1024 - yep, same DEBUG message / connection terminated with that line updated to 02

**Comment by EHylands** [comment]
> @EHylands I have the B8512G, and 0x06 works for me. There's also 0x62, which is supposed to be a combination of 0x06 and 0x3E -- but I haven't tried it. When you say that "subscriptions for pushed notifications are not working" is that because the Sanjay's library doesn't implement them, or because of another limitation of the Solutions panels?
> 
> 
> 
> @t3h-n00b Does the same thing happen if you replace [this](https://github.com/mag1024/bosch-alarm-mode2/blob/master/bosch_alarm_mode2/panel.py#L216) 0x01 with 0x02 (requesting *User Based Remote Access*, instead of the *Automation* user)? 

Subscriptions are not yet available on Solution panels (firmware limitation)

Did got US panels and Solution panels working on my Homebridge plugin, lot of ugly code hack though !

**Comment by mag1024** [comment]
Ok, so what I'm hearing is that supporting different panels is a lot of work, and is hard to do without somebody with access to one doing the development.
I think my plan will be this:
1. Update the README to indicate that this library has only been tested with B8512G, and doesn't work with Solution panels, and add a link to Sanjay's project (I've just become aware of it with this issue).
2. Longer term contact Sanjay, and see if he's interested in collaborating on merging our two implementations.

**Comment by sanjay900** [comment]
@t3h-n00b Just FYI, solution 3000 support was added to this integration, we merged my integration and this one together
