### ISSUE TITLE
AMAX and polling vs subscription

### ISSUE THREAD

**Issue by sanjay900** [mag1024/bosch-alarm-mode2#30]
I learned the other day that while AMAX panels don't support Mode 2 subscriptions, they do support another protocol where they push updates, DC-09. 

Do we think it would be worth implementing DC-09 support, or should we just leave AMAX with only polling? 
I just don't know if its worth the development time or not, though there are existing DC-09 implementations out there iirc.

**Comment by mag1024** [comment]
Well, I certainly don't think we should try to support DC-09 in a library called "mode2" 😺 
I suppose this protocol could be added to the integration using some other (existing) library -- but, TBH, I'm not particularly excited about that either.

**Comment by sanjay900** [comment]
Yeah neither am i, ill just close this
