### ISSUE TITLE
Overhaul error codes

### ISSUE THREAD

**Issue by sanjay900** [mag1024/bosch-alarm-mode2#31]
Maybe instead of throwing generic exceptions when things fail, we construct some actual error codes when we throw exceptions? That way, home assistant can just make use of those directly instead of needing to construct its own, and we can even do more specific exceptions like potentially seperate exceptions for automation code failures vs user code vs installer code failures?

**Comment by mag1024** [comment]
As we discussed on another issue, we should definitely have a custom exception for NAKs, and catch them explicitly.
Beyond that, I'm not sure how much else there is to do. I don't think it would be very pythonic to try to wrap standard exceptions (e.g. those produced by asyncio) with our own, and differentiating between the different code failures programmatically/at runtime (which is what different exception types would allow one to do) doesn't seem all that useful - a description exception message (or note) seem adequate.

**Comment by sanjay900** [comment]
Yeah i guess i was more thinking along the lines of having easier to localise error messages like "ERROR_INCORRECT_INSTALLER_CODE" or something for auth errors, which we could then leverage easier from home assistant for authentication issues?

I mostly just want to have seperate errors for installer vs automation code with the amax panels
