### ISSUE TITLE
Permission check causes problems if a panel is currently armed

### ISSUE THREAD

**Issue by sanjay900** [mag1024/bosch-alarm-mode2#40]
A while back i implemented a permission check, with https://github.com/mag1024/bosch-alarm-mode2/pull/35
At the time i validated privileges by checking for history privileges. This however causes issues if a panel is armed, as the panels lock access to the history memory while the panel is armed. This means a user is not able to connect to an armed panel.

We will have to find some other way to validate credentials.
I wonder if any of the other permissions we can check for are enough to validate if a user has master code functions or not.

**Comment by sanjay900** [comment]
If i remember correctly the only command that cares about this is the history command, so maybe we do a permission check before we load history events?

**Comment by mag1024** [comment]
Why do we even need the permission check in the first place?
What happens if you try to do the history fetch without having the requisite permissions? Will it NACK? We can just catch that...

**Comment by sanjay900** [comment]
Yeah im happy with a try catch, would we ever hit a NACK with `('NACK: ', 'Non-specific error')` in any other case do you think?
